provider "aws" {
  region = "ap-south-1"
  access_key = "AKIA4ZHE2NASLMUI6MW5"
  secret_key = "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"
}

resource "aws-instance" "myfirst" {
  ami = "ami-01b99a419451fe564"
  instance_type = "t2.micro"
  key_name = "ubantu"
  security_groups = ["ALL TCP N PING"]
}

resource "aws_security_group" "allow_tls" {
  name        = "allow_tls"
  description = "Allow TLS inbound traffic"
  vpc_id      = ""

  ingress {
    # TLS (change to whatever ports you need)
    from_port   = 443
    to_port     = 443
    protocol    = "-1"
    # Please restrict your ingress to only necessary IPs and ports.
    # Opening to 0.0.0.0/0 can lead to security vulnerabilities.
    cidr_blocks = # add a CIDR block here
  }

  egress {
    from_port       = 0
    to_port         = 0
    protocol        = "-1"
    cidr_blocks     = ["0.0.0.0/0"]
    prefix_list_ids = ["pl-12c4e678"]
  }
}